- name: copy a config file
  ansible.builtin.copy:
    src: ../ansible.iphilka.ru.conf
    dest: "{{ nginx_available }}/ansible.iphilka.ru.conf"
    owner: root
    group: root
    mode: 0755

- name: link configs
  ansible.builtin.file:
    src: "{{ nginx_available }}/ansible.iphilka.ru.conf"
    dest: "{{ nginx_enabled }}/ansible.iphilka.ru.conf"
    state: link

- name: remove default link
  ansible.builtin.file:
    path: "{{ nginx_enabled }}/default"
    state: absent
    
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted